import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

export function registerWorkChecklistTool(server: McpServer) {
  server.tool(
    'generate_work_checklist',
    '업무 체크리스트 작성을 위한 가이드라인과 프롬프트를 반환합니다. 학교 업무(학기초, 학기말, 행사, 평가 등)를 체계적으로 관리할 수 있는 체크리스트 지침을 제공합니다. 결과물은 export_hwpx의 checklist 템플릿으로 HWPX 파일로 출력할 수 있습니다.',
    {
      content: z.string().describe('체크리스트로 만들 업무 내용 또는 참고 문서 (공문, 지침, 메모 등)'),
      checklist_title: z.string().optional().describe('체크리스트 제목 (예: "학기초 업무 체크리스트")'),
      checklist_type: z.enum(['semester_start', 'semester_end', 'event', 'evaluation', 'safety', 'custom']).default('custom').describe('유형: semester_start=학기초, semester_end=학기말, event=행사, evaluation=평가, safety=안전점검, custom=직접입력(기본)'),
      deadline: z.string().optional().describe('전체 마감일 (예: "2026. 5. 30.")'),
      responsible: z.string().optional().describe('담당자 (예: "1학년부")'),
      instructions: z.string().optional().describe('추가 지침'),
    },
    async (params) => {
      const title = params.checklist_title || '업무 체크리스트';

      const typePresets: Record<string, string> = {
        semester_start: [
          `### 학기초 업무 예시 항목`,
          `- 교실 환경 정비 (게시판, 좌석, 사물함)`,
          `- 학급 편성 및 출석부 확인`,
          `- 교과서/부교재 배부`,
          `- 학부모 총회 준비`,
          `- 학급 규칙 수립`,
          `- 학생 건강조사표 수합`,
          `- 긴급 연락망 구성`,
          `- 방과후 프로그램 안내`,
        ].join('\n'),
        semester_end: [
          `### 학기말 업무 예시 항목`,
          `- 성적 처리 (성적 입력, 검증)`,
          `- 생활기록부 작성`,
          `- 교과서 회수`,
          `- 교실 정리 및 비품 점검`,
          `- 학부모 상담 결과 정리`,
          `- 학급 활동 기록 정리`,
          `- 다음 학기 인수인계 준비`,
        ].join('\n'),
        event: [
          `### 행사 준비 업무 예시 항목`,
          `- 행사 계획서 작성 및 결재`,
          `- 장소 섭외/예약`,
          `- 가정통신문 발송`,
          `- 참가 동의서 수합`,
          `- 보험 가입`,
          `- 안전 교육 실시`,
          `- 차량/이동 수단 확인`,
          `- 비상 연락망 구성`,
        ].join('\n'),
        evaluation: [
          `### 평가 업무 예시 항목`,
          `- 평가 계획 수립 및 결재`,
          `- 시험 문제 출제 및 검토`,
          `- 시험지 인쇄 및 봉인`,
          `- 감독 일정 배정`,
          `- 답안지 채점 및 이의신청`,
          `- 성적 입력 및 검증`,
          `- 성적표 배부`,
        ].join('\n'),
        safety: [
          `### 안전점검 예시 항목`,
          `- 소화기 점검 (위치, 유효기간)`,
          `- 비상구 확인 (통행 가능 여부)`,
          `- 전기 시설 점검`,
          `- CCTV 작동 확인`,
          `- 놀이시설 안전 점검`,
          `- 급식실 위생 점검`,
          `- 비상 대피로 확보`,
        ].join('\n'),
        custom: `### 사용자 입력 기반으로 항목을 추출합니다.`,
      };

      const guideMarkdown = [
        `# 업무 체크리스트 생성 가이드`,
        ``,
        `## 입력 정보`,
        `- 제목: ${title}`,
        `- 유형: ${params.checklist_type}`,
        params.deadline ? `- 마감일: ${params.deadline}` : '',
        params.responsible ? `- 담당: ${params.responsible}` : '',
        ``,
        `## 참고 내용`,
        `${params.content}`,
        ``,
        params.instructions ? `## 추가 지침\n${params.instructions}\n` : '',
        `## 유형별 참고`,
        ``,
        typePresets[params.checklist_type],
        ``,
        `## 체크리스트 작성 규칙`,
        ``,
        `### 항목 구성`,
        `1. **카테고리**: 업무를 3~5개 카테고리로 분류`,
        `2. **항목**: 각 카테고리 아래 구체적 할 일 (동사형)`,
        `3. **기한**: 각 항목의 완료 기한 (D-day 기준)`,
        `4. **담당자**: 각 항목의 책임자`,
        `5. **비고**: 참고 사항, 주의 사항`,
        ``,
        `### 작성 원칙`,
        `- 항목은 **동사형**으로 시작 ("확인한다", "제출한다", "배부한다")`,
        `- **구체적**이고 **측정 가능**하게 (완료 판단 기준 명확)`,
        `- 기한이 이른 것부터 배치 (시간순)`,
        `- 필수/선택 구분 (★ 필수, ○ 선택)`,
        ``,
        `### 표 형식`,
        `- 열: 순번, 카테고리, 항목, 기한, 담당, 완료(☐), 비고`,
        `- 체크박스: "☐" (미완료), "☑" (완료)`,
        ``,
        `## HWPX 출력 방법`,
        ``,
        `\`export_hwpx\` 도구를 사용하여 HWPX 파일로 출력하세요.`,
        ``,
        `### export_hwpx 파라미터`,
        `- **template**: \`"checklist"\``,
        `- **section_xml**: 아래 채울 자리 표시에 내용을 넣어 전달`,
        ``,
        `### 채울 자리 표시 매핑 (checklist 템플릿)`,
        `- {{제목}}: ${title}`,
        `- {{학년도}}: 해당 학년도 (예: "2026")`,
        `- {{학급}}: 학급명 (예: "6학년 3반")`,
        `- {{기간}}: ${params.deadline || '점검 기간'}`,
        `- {{담당교사}}: ${params.responsible || '담당 교사명'}`,
        `- {{점검목적}}: 체크리스트 목적 설명`,
        `- {{작성일}}: 작성 일자`,
        `- {{기호안내}}: 기호 범례 (예: "★ 필수, ○ 선택, ☐ 미완료, ☑ 완료")`,
        `- {{체크리스트표}}: 체크리스트 본문 표 (markdown 표 → OWPML 자동 변환)`,
        `- {{비고}}: 참고 사항`,
        `- {{담당교사 서명란}}: 담당교사 서명 영역`,
        ``,
        `### markdown 표 예시`,
        '```',
        `| 순번 | 카테고리 | 항목 | 기한 | 담당 | 완료 | 비고 |`,
        `|------|----------|------|------|------|------|------|`,
        `| 1 | 학급편성 | 출석부 확인 및 인쇄 | 3/2 | 담임 | ☐ | 교무실 비치 |`,
        `| 2 | 학급편성 | 좌석 배치표 작성 | 3/2 | 담임 | ☐ | |`,
        `| 3 | 환경정비 | 교실 게시판 꾸미기 | 3/4 | 담임 | ☐ | 학급규칙 포함 |`,
        '```',
      ].filter(Boolean).join('\n');

      return {
        content: [{ type: 'text' as const, text: guideMarkdown }],
      };
    },
  );
}
